### ISSUE TITLE
[BUG] `CDS-types` version 8.0.3 different behaviour on standard events ?

### ISSUE THREAD

**Issue by dragolea** [cap-js/cds-types#145]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi,
In the newly version of the `cds-types` we have 7 overloads on the `AFTER`, in the previous version of the `CDS 7` we had only 4 overloads.

<img width="1613" alt="image" src="https://github.com/user-attachments/assets/9b815399-ce31-48a4-b5cc-a023bfbdad9a">

`LEFT IMAGE - CDS version 8`  `RIGHT IMAGE - CDS version 7`

During testing a sample project of the standard events, I was not able to find a suitable applied overload for catching the events + the typing looks wrong if we take in consideration also using the `CDS-Typer`

<img width="1558" alt="image" src="https://github.com/user-attachments/assets/78275e88-16da-4049-ab93-bbbbf61aebbd">

`LEFT IMAGE - CDS version 7`  `RIGHT IMAGE - CDS version 8`

I was not able also to trigger the `EACH` on every `Book` analogue to the `Array.prototype.forEach`, practically it doesn't stop.

### Expected Behavior

1. Typing should follow the Entity or should be corrected based on the `CDS-Typer entity`
2. 

### References

CDS Version 8.0.3

### Versions

`This version all overloads are working as expected`

| @dxfrontier/cds-ts-dis | git+https://github.com/dxfrontier/cds-ts-dispatcher.git                        |
| ---------------------- | ------------------------------------------------------------------------------ |
| @cap-js/asyncapi       | 1.0.1                                                                          |
| @cap-js/cds-typer      | 0.23.0                                                                         |
| @cap-js/openapi        | 1.0.4                                                                          |
| @cap-js/sqlite         | 1.7.3                                                                          |
| @sap/cds               | 7.9.3                                                                          |
| @sap/cds-compiler      | 4.9.6                                                                          |
| @sap/cds-dk (global)   | 8.0.2                                                                          |
| @sap/cds-fiori         | 1.2.7                                                                          |
| @sap/cds-foss          | 5.0.1                                                                          |
| @sap/cds-mtxs          | 2.0.2                                                                          |
| @sap/eslint-plugin-cds | 3.0.4                                                                          |
| Node.js                | v22.4.1                                                                        |

`This version somehow the overloads are acting awkard`

| cds8test               | <Add your repository here>                                                 |
| ---------------------- | -------------------------------------------------------------------------- |
| @cap-js/asyncapi       | 1.0.1                                                                      |
| @cap-js/cds-typer      | 0.23.0                                                                     |
| @cap-js/cds-types      | 0.6.0                                                                      |
| @cap-js/openapi        | 1.0.4                                                                      |
| @cap-js/sqlite         | 1.7.3                                                                      |
| @sap/cds               | 8.0.3                                                                      |
| @sap/cds-compiler      | 5.0.6                                                                      |
| @sap/cds-dk (global)   | 8.0.2                                                                      |
| @sap/cds-fiori         | 1.2.7                                                                      |
| @sap/cds-foss          | 5.0.1                                                                      |
| @sap/cds-mtxs          | 2.0.2                                                                      |
| @sap/eslint-plugin-cds | 3.0.4                                                                      |
| Node.js                | v22.4.1                                                                    |

**Comment by hakimio** [comment]
Change from `data: Book` to `data: Books` seems to be intentional: https://github.com/cap-js/cds-types/pull/45

**Comment by dragolea** [comment]
Correct, this is option to have the typing `specified inside of the callback`
But somehow `AFTER` does not work like before, for `EACH` and also for normal `READ`.

**Comment by dragolea** [comment]
Hi Daniel

Thanks for taking time to have a look over the issue.

```ts
import { Book, Books } from '#cds-models/CatalogService'
import cds from '@sap/cds'

class BooksService extends cds.ApplicationService {
  init() {
    this.after('READ', Books, (data, req) => {
      // data is of type Book and not Books
      debugger
    })

    // This is not triggered anymore like analogue forEach
    this.after('EACH', Books, (data, req) => {
      debugger
    })

    return super.init()
  }
}

module.exports = BooksService
```

I can create a very small repo example if you are not sure about code above.

**Comment by stockbal** [comment]
I created PR #151 and a sample project with runtime tests. The PR should fix the current type inference apart from `.drafts`. If the handler registration should work for drafts the same way then the singular entity should get `drafts: typeof Singular` and the plural entity `drafts: typeof Plural`.

**Comment by dragolea** [comment]
Hi @daogrady,
Is above PR all right, above issue are showstopper for TS projects as `AFTER` is a core event.

**Comment by dragolea** [comment]
?

**Comment by Mischa1610** [comment]
We would also be pretty happy to see progress on this topic because we also use the cds-ts-dispatcher package and this is blocking us from updating to CDS8. If we can support testing PR or some fixes just let us know, happy to help.

Here is the issue in cds-ts-dispatcher that documents the progress on "supporting" CDS 8: https://github.com/dxfrontier/cds-ts-dispatcher/issues/85

FYI @mvk-abs

**Comment by daogrady** [comment]
Hi @stockbal @dragolea @Mischa1610 @hakimio ,

the PR looks good to me. Sorry for the delay everyone. and thanks for the contribution, Ludwig! Let's get this merged and released asap. 

Best,
Daniel
