### ISSUE TITLE
Wrong type on services.d.ts for preprend method

### ISSUE THREAD

**Issue by bvincent** [cap-js/cds-types#16]
Hello,

Since the cds 7.5 version, the preprend method on class Service is no more async (services.d.ts).

`prepend(fn: ServiceImpl): Promise<this>`

should now be:

`prepend(fn: ServiceImpl): this`

Thanks

**Comment by daogrady** [comment]
Hi @bvincent ,

thank you for reporting this issue!
@johannes-vogel I can see that [CAPire](https://cap.cloud.sap/docs/node.js/core-services#srv-prepend) also still has this as `async`, while the implementation indeed seems to be synchronous. Can you clear up what the correct signature should be?

Best,
Daniel

**Comment by daogrady** [comment]
Hi @bvincent,

I was informed that the method has indeed changed from async to sync. We will address this shortly. Thanks for the report!

Best,
Daniel

**Comment by bvincent** [comment]
Thanks for the fix.
