### ISSUE TITLE
Support for cds.compile() in Typescript

### ISSUE THREAD

**Issue by i555819** [cap-js/cds-types#17]
We would like to use cds.compile as mentioned in the following https://cap.cloud.sap/docs/node.js/cds-compile#cds-compile. We want to pass in multiple in-memory sources as it mentions. However, there are two problems:

1. This method is not available in Typescript. We have found that `const cds = require('@sap/cds-dk');` is a workaround in which we are able to use cds.compile for multiple sources. 
2. Using cds.compile for multiple sources requires you to add in the `@sap/cds/common.csn` definitions yourself. It would be nice if these definitions could be automatically added from common.cds. Currently we are manually reading the file from `node_modules/@sap/cds/common.cds` to retrieve these definitions. 

Here is the full current solution/workaround to these problems, however it is not that elegant so we are wondering if there are any plans to implement the above items or a better solution. 

```js
  const cds = require('@sap/cds-dk');
...
  const commonFileData = readFileSync(path.resolve(__dirname, '.../@sap/cds/common.cds'), 'utf-8');
  const cdsCommonDefinitions = cds.compile(commonFileData);

  const csn = cds.compile({
    'db/schema.cds': <cds data>,
    'srv/services.cds': <service data>,
    '@sap/cds/common.csn': `${JSON.stringify(cdsCommonDefinitions)}`,
  });
```

**Comment by daogrady** [comment]
Hi @i555819 ,

thank you for reaching out to us. `cds.compile` is available with [several overloads](https://github.com/cap-js/cds-types/blob/main/apis/models.d.ts#L93) in the current types. Do any of those do what you need?

Best,
Daniel

**Comment by daogrady** [comment]
@johannes-vogel regardless, CAPire suggests passing the `options` as second parameter after the model. [The overload matching most closely](https://github.com/cap-js/cds-types/blob/main/apis/models.d.ts#L129) does not expect a second parameter. Should we have this second parameter or is CAPire wrong here?

**Comment by chgeo** [comment]
Before going in the type details here, @i555819 can you shed some light on why you use this advanced API?
Normally, to compile a couple of files, you would just use [`cds.load`](https://cap.cloud.sap/docs/node.js/cds-compile#cds-load) like
```js
const cds = require('@sap/cds')
const csn = cds.load('*') // * means db, srv, app folders
// or 
cds.load('srv')
// or 
cds.load('srv/services.cds')
// or 
cds.load(['db', 'srv'])  // `db` is not needed here, as `srv` imports it
```

The compile API that you use right now is designed for scenarios where there are no files, but you in-memory strings.  These need to be given their import resolutions explicitly, hence the more involved API.

`cds-dk` does not play a role here btw.  All API is available from `@sap/cds`.

**Comment by i555819** [comment]
Hi @chgeo, we would like to implement it this way because we do not have any files and we only have in-memory CDL strings, as you mentioned. We are creating the CDL strings ourselves and so would like to compile those into CSN. 
It would be ideal to not have to provide the import resolutions ourselves, as well as having this compile API available for Typescript as our team does not want to have a 'require' statement in the code.

You are right about not needing cds-dk, I have changed that.

**Comment by i555819** [comment]
@daogrady Thanks for the update. For now we have decided to use cds.parse to compile each of the two models separately. This method does not add the `managed` fields in the CSN but for our use case we don't think that should be an issue. If you see any problem with using cds.parse instead of cds.compile let me know.

**Comment by daogrady** [comment]
@i555819 I don't think there is an issue with using `cds.parse` instead. Glad you were able to work it out!
