### ISSUE TITLE
Use interface for cds_services to allow module augmentation

### ISSUE THREAD

**Issue by aschmidt93** [cap-js/cds-types#185]
`cds.services` is currently typed as type `cds_services`: `export type cds_services = { [name: string]: Service }`. Types can not be extended via module augmentation, thus this does not work:

```ts
// index.d.ts
import "@sap/cds";

declare module "@sap/cds" {
  export declare type cds_services = { foo: "bar" };
}
```

`cds.services` would still be typed as `{ [name: string]: Service }`.

In order for module augmentation to work, `cds_services` has to be an interface. 

## Idea

```ts
declare module "@sap/cds" {
  type service_dict = { [name: string]: Service }
  export interface cds_services extends service_dict {}
}
```

Now module augmentation can be used to extend `cds_services`:

```ts
// index.d.ts
import "@sap/cds";

declare module "@sap/cds" {
  export interface cds_services {
    foo: "bar";
  }
}
```

Now, `cds.services.foo` is properly typed as "bar".

## Reason

This can be used to narrow down the type of `cds_services` to only those services that actually exist in the project. Additionally, `cds-typer` can be used to type those services.

**Comment by daogrady** [comment]
Hi Andreas,

thank you for your suggestion. I am actually not sure if module augmentation is the right approach here, as that is kind of a "last resort" technique and here it is used for added convenience. Wouldn't a [helper type](https://www.typescriptlang.org/play/?#code/PTAEBMFcFtoTwFAGMD2A7AzgF1E8GB9DAUwCcA3ASyWI1AF5QBvBUN0eAZTKpoEEAXKAAsAJgA0rdlx7ViAISEBaMQgC+CBFjgAHYqACycbhTl1GAchmn+F0AB9QV47JryLmkKG17QAc0gAQ1JwcVBA8HBicFAAI2I0YgAzShwUJPCkLCCAGxy4b0CAa0o0P1xg-XTQUkg0LEpofXJAnMpwQIb0cLoAd2I80AALLCwdDAEQXumAOh9aJFJKHSwcwLKZlFI-YHAUJAxgIfXwWJQUIuAIlrQacCV5jBmR6ByEJLqsym7KDAB5RJ-JJGEy8WigAAUGBQTVBciE2CWZQAlAiYcQ4TRQL9DC4bOCWOwasRsqQ0KAANrOTHEPgWMLU1wKCwAXRmpSQOUgUQwUPRNOR6k0H1uXXJgSQNBW-zQ+RBTLoUKZADlAk0hPL8RhkcwpGwvP0KuT4rh0CkovVQNUSPjVU04sRSuV0FUMihIKRQDawRg9abMCgcsQZjkUH4IRZelsihgLIKNO9PmKveiAGJJ75oACqGCdfBpkO9cjtxARWCRfh1hPYlAyEIAhL8AcQgZqfUrbWriMidaQSR60H6JVKsDK5Xj20WaCX40A) appropriately address the underlying issue?

Best,
Daniel

**Comment by aschmidt93** [comment]
Hi Daniel,

sorry for the late response. I do think module augmentation is the right approach here unless there's a way for cds-types to automatically pick up the services generated by cds-typer and type `cds_services` accordingly. 

The alternative would be to manually type each time a service is accessed:

```ts
// `OrderServiceTypes` is the file generated by cds-typer (import type * as OrderServiceTypes from "...")
// TypedService is a custom type that uses the output of cds-typer to type the generic methods of a service, e.g. `send` or `emit`
const orderService : TypedService<typeof OrderServiceTypes> = cds.services["OrderService"];

// compile time checked with `TypedService`
await orderService.emit("foo", {bar : 0});
```

I think this is cumbersome and prone to error, especially in a larger code base with many service-to-service interactions. Therefore, module augmentation fits perfectly. It allows users to define once in a central place which services are available and additionally users can type those services, if they choose to. Additionally, it requires no runtime code. And the change required in cds-types is miniscule, isn't it?

**Comment by daogrady** [comment]
Hi Andreas,

sorry for the late response as well. 🙂
I have no strong sentiment towards using `type` or `interface` here. But as this is a rather fundamental change, I'd like to give it a more thorough look. I'll have to postpone it until mid November, as I will be ooo for the next two weeks. Just giving a headsup.

Best,
Daniel

**Comment by daogrady** [comment]
Hi Andreas,

I looked into your suggestion and I am still not super stoked about this solution. Not because of the `type` vs `interface` debate, but because it requires users to locally patch around in cds-types and is still extremely error prone.
Think you rely on `cds_services` containing only valid services. But you changed your model, added some services, or removed an existing service without adjusting your model augmentation accordingly[^1]. Now you'd still be using wrong values, but with more confidence, which -- in my opinion -- is even worse.

But if you consider this helpful for your scenario then I will not block it.

Best,
Daniel

[^1]: this is basically where we were before cds-typer, when users would manually define TS types for their model, which would eventually run out of sync with their actual model.

**Comment by aschmidt93** [comment]
I agree. I see this more as a "better than nothing" solution until we have a (half-)fully automated solution.
