### ISSUE TITLE
[QUESTION] How to read from db using types?

### ISSUE THREAD

**Issue by ThePlenkov** [cap-js/cds-types#220]
### Question

Hi! I'd like to write a function like this:

```
 const { OBJECTS } = await import('./types/index');
const result = await db.read(OBJECTS)
```
However currently i have a following type error:
```
No overload matches this call.
  Overload 1 of 2, '(entity: ArrayConstructable<any>, key?: any): Awaitable<SELECT_3<ArrayConstructable<any>>, any[]>', gave the following error.
    Argument of type 'typeof OBJECTS' is not assignable to parameter of type 'ArrayConstructable<any>'.
      Type 'OBJECTS' is missing the following properties from type 'any[]': length, pop, push, concat, and 29 more.
  Overload 2 of 2, '(entity: string | Definition_2, key?: any): SELECT_3<unknown>', gave the following error.
    Argument of type 'typeof OBJECTS' is not assignable to parameter of type 'string | Definition_2'.
```

This is very hard to understand what this message means. I see docs - there is a different pattern on usage - but I didn't see anywhere using db directly to consume entity using generated type.

Would appreciate any advice.
Thanks! 
Petr

**Comment by daogrady** [comment]
Hi Petr,

thanks for approaching us about this issue. I am currently in the process of reworking the QL types, which should hopefully streamline how the different ways to express columns selection work. On first glance it looks like your use case would be covered by the rework as well; so stay tuned for the next release. 🙂
Glad you found a solution to fix your problem for now!

Best,
Daniel
