### ISSUE TITLE
[FEATURE] fully-typed orderBy

### ISSUE THREAD

**Issue by ThePlenkov** [cap-js/cds-types#227]
### Question

Hi!

I want to implement the order when selecting from the generated entity. It works well for building the projection and filtering, however I'm struggling to udnerstand what should be the sorting pattern. So far I'm only able to provide fields as a string, which is OK but would be better to use types somehow. Thanks!

**Comment by daogrady** [comment]
Hi Petr,

that sounds like a reasonable addition. I will see if this fits in with a current [rework](https://github.com/cap-js/cds-types/pull/201) of the QL types.

Also, I have transferred this issue over to [cds-types](https://github.com/cap-js/cds-types) too, as this is also related to how the cds runtime handles input and what kind of overloads are being offered and is unrelated to the generation of type information for the CDS model (cds-typer).

Best,
Daniel

**Comment by ThePlenkov** [comment]
thanks for transferring. Can we also change labels, since is now more like a feature proposal?
