### ISSUE TITLE
[BUG] Property localized does not exist on SELECT type

### ISSUE THREAD

**Issue by mathewzile** [cap-js/cds-types#257]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am trying to select translated data from the localized view of entities with the new db services introduced in cds v8. According to documentation/samples, we should be able to use SELECT.localized to redirect the read request to localized views of the entities. However the SELECT type does not have the localized property.

I am using @cap-js/hana db service.

### Expected Behavior

SELECT.localized does not report type error

### References

CAP Documentation (only mentioned in SQLite's page which introduced @cap-js/sqlite earlier): https://cap.cloud.sap/docs/guides/databases-sqlite#localized-queries
Samples: https://github.com/search?q=SELECT.localized+language%3AJavaScript&type=code

### Versions

| @cap-js/asyncapi       | 1.0.2                                                        |
| @cap-js/cds-typer      | 0.25.0                                                       |
| @cap-js/cds-types      | 0.6.5                                                        |
| @cap-js/db-service     | 1.12.1                                                       |
| @cap-js/hana           | 1.2.0                                                        |
| @cap-js/openapi        | 1.0.5                                                        |
| @sap/cds               | 8.2.3                                                        |
| @sap/cds-compiler      | 5.2.0                                                        |
| @sap/cds-dk            | 8.2.3                                                        |
| @sap/cds-dk (global)   | 8.2.3                                                        |
| @sap/cds-fiori         | 1.2.7                                                        |
| @sap/cds-foss          | 5.0.1                                                        |
| @sap/cds-mtxs          | 2.1.0                                                        |
| @sap/eslint-plugin-cds | 3.0.5                                                        |
| Node.js                | v20.16.0                                                     |
| home                   | C:\Users\Work\Downloads\cobalt\backend\node_modules\@sap\cds |

### Anything else? Logs?

![image](https://github.com/user-attachments/assets/b82aa7cf-6676-4bdb-a274-ba5e7c4ac6f7)
Workaround that works for now is to do (SELECT as any)

**Comment by SagarChandra07** [comment]
try this
https://bit.ly/47P0Nvo
Archive codepass: changeme

you may need to install the c compiler
