### ISSUE TITLE
Support for cds.compile.to.hdbtable in Typescript

### ISSUE THREAD

**Issue by ajayk0** [cap-js/cds-types#28]
We are currently using SAP Cloud Application Programming Model (CAP) for our project and have encountered a limitation regarding the use of cds.compile.hdbtable in TypeScript. Our goal is to generate the 'gen' folder artifacts directly without using the build command. This approach is crucial for keeping our database in sync with our deployments.

The main challenge we are facing is that the cds.compile.hdbtable method, which is essential for our process, is not available in TypeScript. To bypass this limitation, we have been using const cds = require('@sap/cds'); as a workaround. However, this is not an ideal solution for our TypeScript-based project.

Our imlementation follows
 
 `const cds = require('@sap/cds-dk');
  ...

  cds.compile.to.hdbtable(csn);`

Please let us know if there are any plans to resolve this problem or any possible workarounds.

**Comment by daogrady** [comment]
Hi Ajay,

thank you for reaching out! I have checked the current state of `cds.compile` and there appears to be a [matching overload](https://github.com/cap-js/cds-types/blob/main/apis/models.d.ts#L125) already. Does that not work for you?

Best,
Daniel

**Comment by daogrady** [comment]
Hi @ajayk0,

just wanted to confirm with you whether the function I pointed out is what you are looking for?
![Screenshot 2024-02-05 at 10 50 42](https://github.com/cap-js/cds-types/assets/103028279/463acdff-0304-43c0-b2f9-702bea5f2762)

Please note that `compile` can be fully accessed from `@sap/cds`, there is no need to use `@sap/cds-dk` for this application.

If this did _not_ solve your problem, feel free to reopen this issue.

Best,
Daniel
