### ISSUE TITLE
[BUG] Logger class is not exported

### ISSUE THREAD

**Issue by sebastien-savalle** [cap-js/cds-types#281]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

`cds.log` returns an instance of Logger but the definition of this class is not exported. So, we can't import it and use this type for variable definition.

### Expected Behavior

I would expect to be able to import Logger.

Something like that
`import { Logger } from '@sap/cds';`

which should allow:
`private readonly logger: Logger;`

### References

Actually, if we want to avoid ts-ignore, we have to use something like in every method:
```
const logger = cds.log('test');
logger.error('Logger type is not exportable');
```

We can't instantiate the logger in a constructor.

### Versions

| dependency     | https://github.com/<your/repo>                                                               |
| ---------------------- | -------------------------------------------------------------------------------------------- |
| @cap-js/asyncapi       | 1.0.2                                                                                        |
| @cap-js/cds-types      | 0.6.5                                                                                        |
| @cap-js/openapi        | 1.0.6                                                                                        |
| @sap/cds               | 8.3.1                                                                                        |
| @sap/cds-compiler      | 5.3.2                                                                                        |
| @sap/cds-dk            | 8.3.0                                                                                        |
| @sap/cds-fiori         | 1.2.7                                                                                        |
| @sap/cds-foss          | 5.0.1                                                                                        |
| @sap/cds-mtxs          | 2.2.0                                                                                        |
| @sap/eslint-plugin-cds | 3.1.0                                                                                        |
| Node.js                | v20.15.1                                                                                     |

**Comment by daogrady** [comment]
Hi Sébastien,

thanks for the report! While we fix this, you can bandaid-fix this like so:

```ts
type Logger = ReturnType<cds.log>
```

Best,
Daniel

**Comment by daogrady** [comment]
Hi Sébastien,

for technical reasons, we decided not to expose this type for now. But the solution described above should work just fine and is actually quite common to do.

Best,
Daniel
