### ISSUE TITLE
Compatibility with Vitest

### ISSUE THREAD

**Issue by i555819** [cap-js/cds-types#29]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

We are using @sap/cds in Typescript. We are using Vitest for our test cases, and are encountering an error with using `import cds from '@sap/cds';` When we use an import statement, all calls to i.e. `cds.run(query)` cause the tests to fail with `TypeError: default.run is not a function`. However, this issue does not occur if we change all the import statements to use `require` instead. 

### Expected Behavior

We would like to run our Vitest tests and be able to use `import cds from '@sap/cds';` instead of `const cds = require('@sap/cds');`

### References

We think this line https://github.tools.sap/cap/cds/blob/main/lib/index.js#L143 is preventing using ESM for importing cds

### Versions

| Node.js                | v20.7.0     |
| @sap/cds               | 7.5.2       |
| @sap/cds-compiler      | 4.5.0       |
| @sap/cds-dk            | 7.4.1       |
| @sap/cds-dk (global)   | 7.4.1       |
| @sap/eslint-plugin-cds | 2.6.4       |
| @sap/cds-mtxs          | 1.13.1      |

Repo: 
https://github.tools.sap/AppGyver/appgyver-cloud-functions-runner/tree/feature/unified-vcf-runner-with-cap-runtime

**Comment by i555819** [comment]
Hi @ogrady, could we please get any update or guidance on this issue? Thanks!

**Comment by ogrady** [comment]
Hi @i555819,

I am currently out of office with no access to my working devices. I will asap look into this matter next week.

Best,
Daniel

**Comment by daogrady** [comment]
Hi @i555819,

I am currently trying to reproduce the issue but am running into trouble setting up your project as it apparently requires access to an internal registry, which I do not have.
Could you please provide a minimal reproducible example so I can look into the issue?

Best,
Daniel

**Comment by i555819** [comment]
@daogrady I opened an issue in the main place for cap issues here for more visibility: https://github.tools.sap/cap/issues/issues/15465 with instructions to reproduce it.

**Comment by daogrady** [comment]
Hi @i555819 ,

thank you for the MRE. I can reproduce the problem now. Will continue in the newly opened issue.

Best,
Daniel
