### ISSUE TITLE
[BUG] Missing types for cds.minify and cds.compile.for.nodejs()

### ISSUE THREAD

**Issue by BastiInnovation** [cap-js/cds-types#292]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

My Backend is running with nestjs. You can find my Project here: https://github.com/BastiInnovation/cap-template. 

While compiling the project i received two errors: 

> Property 'minify' does not exist on type 'typeof import("@sap/cds")'.

> Property 'nodejs' does not exist on type '{ odata(model: CSN, o?: _options): CSN; sql(model: CSN, o?: _options): CSN; }'. 

Currently the typedefinitions for .minify and .nodejs are missing in cds-types
```TypeScript
 const csn = await cds.load('cds').then(cds.minify) // Type is missing
 cds.model = cds.compile.for.nodejs(csn) // Type is missing
```

### References

Here the references to CAPier articles: 
[cds.minify](https://cap.cloud.sap/docs/node.js/cds-compile#cds-minify)

cds.compile.for.nodejs as not yet been documented.

### Versions

| appname                | https://github.com/BastiInnovation/cap-template                                                  |
| ---------------------- | ------------------------------------------------------------------------------- |
| @cap-js/asyncapi       | 1.0.2                                                                           |
| @cap-js/cds-typer      | 0.27.0                                                                          |
| @cap-js/openapi        | 1.0.6                                                                           |
| @sap/cds               | 8.3.1                                                                           |
| @sap/cds-compiler      | 5.3.2                                                                           |
| @sap/cds-dk            | 8.3.0                                                                           |
| @sap/eslint-plugin-cds | 3.1.0                                                                           |
| Node.js                | v20.11.0

**Comment by Markus-Schroeder-de** [comment]
call in the root "npm rebuild" and check if you have the sym link in the npm-registry with the cds__ (double underscore) see https://github.com/cap-js/cds-types/issues/251

**Comment by daogrady** [comment]
Hi @BastiInnovation ,

I will look into the missing `.minify`, but `compile.for.nodejs` appears to not/ no longer be supported:

```sh
> cds c --help

  ...
  -4 | --for <target>

    Unfolds the compiled CSN for the specified <target> usages,
    or get a comma-separated list, without generating target formats.
    Currently supported:

    - odata
    - sql
```

Best,
Daniel

**Comment by BastiInnovation** [comment]
Hi @daogrady, 
thank u for u quick reply. Yesterday I got the information from SAP support that i have to use  `compile.for.nodejs` if I want to keep my own initialization logic...

Best regards,
Bastian

**Comment by daogrady** [comment]
Hi @David-Kunz ,

thanks for confirming! I have prepared a fix, but I am still unclear on some details. Let's maybe take this opportunity to clear this and a few other questions up in a sync these days.

Best,
Daniel
