### ISSUE TITLE
[BUG] Types of `cds.log` don't match the documentation

### ISSUE THREAD

**Issue by tsteckenborn** [cap-js/cds-types#30]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

`cds.log` is typed as 
```ts
  (name: string, options?: string | number | { level?: number, label?: string, prefix?: string }): Logger,
```

Which doesn't fit the [documentation](https://cap.cloud.sap/docs/node.js/cds-log#cds-log) which says:

```
// all following are equivalent...
const LOG = cds.log('foo', 'warn')  //> shorthand for:
const LOG = cds.log('foo', { level: 'warn' }) <--
// including case-insensitivity...
const LOG = cds.log('foo', 'WARN')  //> shorthand for:
const LOG = cds.log('foo', { level: 'WARN' }) <--
```

### Expected Behavior

These should work and not fail due to `Type 'string' is not assignable to type 'number'.ts(2322)`
```
const LOG = cds.log('foo', { level: 'warn' }) <--
const LOG = cds.log('foo', { level: 'WARN' }) <--
```

### References

https://cap.cloud.sap/docs/node.js/cds-log#cds-log

### Versions

| | |
|:---------------------- | ----------- |
| Node.js                | v20.11.0    |
| @sap/cds               | 7.5.3       |
| @sap/cds-compiler      | 4.5.0       |
| @sap/cds-dk            | 7.5.1       |
| @sap/cds-dk (global)   | 7.6.0       |
| @sap/eslint-plugin-cds | 2.6.4       |
| @sap/cds-mtxs          | 1.14.2      |
| @cap-js/cds-types      | 0.2.0       |

**Comment by daogrady** [comment]
Hi Tobias,

thanks for reporting this issue! I will change `level` to be of type `?: string | number` to be in line with what the documentation says.

Best,
Daniel
