### ISSUE TITLE
[BUG] Test Logging missing typing

### ISSUE THREAD

**Issue by tsteckenborn** [cap-js/cds-types#319]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Using `const log = cds.test.log();` returns
```
Property 'log' does not exist on type '{ (dirname: string): Test; (command: string, ...args: string[]): Test; Test: typeof Test; in(dirname: string): Test; }'.ts(2339)
```

### Expected Behavior

Usage possible as described in the documentation.

### References

See [here](https://pages.github.tools.sap/cap/docs/node.js/cds-test#test-log).

### Versions

| ---------------------- | ------------------------------------------------------------------------------------------ |
| @cap-js/asyncapi       | 1.0.2                                                                                      |
| @cap-js/audit-logging  | 0.8.1                                                                                      |
| @cap-js/cds-typer      | 0.25.0                                                                                     |
| @cap-js/cds-types      | 0.7.0                                                                                      |
| @cap-js/change-trackin | 1.0.7                                                                                      |
| @cap-js/hana           | 1.4.0                                                                                      |
| @cap-js/openapi        | 1.0.7                                                                                      |
| @cap-js/sqlite         | 1.7.5                                                                                      |
| @cap-js/telemetry      | 1.0.1                                                                                      |
| @sap/cds               | 8.4.0                                                                                      |
| @sap/cds-common-conten | 2.1.0                                                                                      |
| @sap/cds-compiler      | 5.4.0                                                                                      |
| @sap/cds-dk            | 8.4.0                                                                                      |
| @sap/cds-fiori         | 1.2.7                                                                                      |
| @sap/cds-foss          | 5.0.1                                                                                      |
| @sap/cds-mtxs          | 2.3.0                                                                                      |
| @sap/eslint-plugin-cds | 3.1.2                                                                                      |
| Node.js                | v20.17.0                                                                                   |

**Comment by daogrady** [comment]
Hi Tobias,

thanks for pointing out this gap! The type will be included in the next release of cds-types.

Best,
Daniel
