### ISSUE TITLE
support locks in cqn

### ISSUE THREAD

**Issue by qby-ankul** [cap-js/cds-types#331]
currently locks are not supported in cqn

https://github.com/cap-js/cds-types/blob/432f34b492eb7a02a222411efad687a44fa6e17c/apis/cqn.d.ts#L10

see docu: https://cap.cloud.sap/docs/cds/cqn#select

**Comment by daogrady** [comment]
Hi @qby-ankul ,

thanks for pointing out these missing properties! They will be included with the next release.

Best,
Daniel

**Comment by patricebender** [comment]
> Hi @daogrady
> 
> if you check, for example, the following link: https://help.sap.com/docs/hana-cloud-database/sap-hana-cloud-sap-hana-database-sql-reference-guide/select-statement-data-manipulation#loio20fcf24075191014a89e9dc7b8408b26__for_update_clause
> 
> `FOR UPDATE [ OF <update_column_name_list> ] [ { <wait_nowait> | **IGNORE LOCKED** } ]`
> 
> Does the SQL statement have other options, including _ignore locked_. In CQN I miss this part at the moment, either because it is not available or not documented.

@johannes-vogel could you jump in here and say something about the `FOR UPDATE` properties?

**Comment by qby-ankul** [comment]
If I see this right, only the `ignore locked` is not implemented.

https://github.com/cap-js/cds-dbs/blob/main/db-service/lib/cqn2sql.js#L447

**Comment by qby-ankul** [comment]
@daogrady Should I reopen my enquiry about forupdate ignore locked in cds dbs?

**Comment by daogrady** [comment]
Hi @qby-ankul ,

as this seems to be a question regarding implementation, that would be the preferred way, yes. Thanks!

Best,
Daniel

**Comment by qby-ankul** [comment]
Ok, then I'll ask about the `of` again.

Thank you very much!
