### ISSUE TITLE
[BUG] `cds.tx` missing

### ISSUE THREAD

**Issue by daogrady** [cap-js/cds-types#36]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The following snippet currently breaks:

```ts
const db = await cds.connect.to("db");
const x = db.tx(req);
```
while the following works:

```ts
const db = await cds.connect.to("db");
const x = db.transaction(req);
```

Old versions of the types show these variants were once both available:

```ts
class cds.service.QueryAPI {
  tx: {
    (fn: (tx: Transaction) => {}): Promise<unknown>
    (context?: object): Transaction
    (context: object, fn: (tx: Transaction) => {}): Promise<unknown>
  }

  transaction: {
    (fn: (tx: Transaction) => {}): Promise<unknown>
    (context?: object): Transaction
    (context: object, fn: (tx: Transaction) => {}): Promise<unknown>
  }
}
```

but the `tx` signature is now gone and only the one for `transaction`[remains](https://github.com/cap-js/cds-types/blob/fe20ce1fa76078c2c008260faac2e0d02d227d71/apis/services.d.ts#L87-L91).

### Expected Behavior

Apparently, it should be the other way around. With `transaction` being deprecated and `tx` [being the advertised in CAPire](https://cap.cloud.sap/docs/node.js/cds-tx).

### References

https://cap.cloud.sap/docs/node.js/cds-tx

DH mentioned `transaction` being deprecated

### Versions

| | https://github.com/<your/repo> |
|:---------------------- | ----------- |
| Node.js                | v19.9.0     |
| @sap/cds               | 7.7.0       |
| @sap/cds-compiler      | 4.6.2       |
| @sap/cds-dk            | -- missing  |
| @sap/cds-dk (global)   | 7.5.1       |
| @sap/eslint-plugin-cds | 2.6.5       |
| @sap/cds-mtxs          | 1.14.0      |
| @cap-js/cds-types      | 0.2.0  |

**Comment by daogrady** [comment]
@johannes-vogel could you please confirm?

**Comment by johannes-vogel** [comment]
Yes, `tx` and `transaction` are equal.

**Comment by daogrady** [comment]
note to self: re-introduce `transaction` as deprecated alias for `tx`
