### ISSUE TITLE
[BUG] read C:\.....\node_modules\@types\sap__cds: Incorrect function. FAILED

### ISSUE THREAD

**Issue by 333sachin** [cap-js/cds-types#364]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I try to deploy using ```cf push``` command I get the below error:

```
read C:\projects\......node_modules\@types\sap__cds: Incorrect function.
FAILED
```
tried doing ```npm rebuild``` before ```cf push``` as well, but still get the same error.

### References

https://community.sap.com/t5/application-development-blog-posts/july-developer-challenge-quot-reverse-apis-quot/ba-p/13749653#toc-hId-165109844

### Versions

 comp                   | <Add your repository here>                       |
| ---------------------- | ------------------------------------------------ |
| @cap-js/asyncapi       | 1.0.2                                            |
| @cap-js/cds-types      | 0.8.0                                            |
| @cap-js/db-service     | 1.16.0                                           |
| @cap-js/openapi        | 1.0.7                                            |
| @cap-js/sqlite         | 1.7.7                                            |
| @sap/cds               | 8.5.0                                            |
| @sap/cds-compiler      | 5.5.2                                            |
| @sap/cds-dk (global)   | 8.5.0                                            |
| @sap/cds-fiori         | 1.2.8                                            |
| @sap/cds-foss          | 5.0.1                                            |
| @sap/cds-mtxs          | 2.4.0                                            |
| @sap/eslint-plugin-cds | 3.1.2                                            |
| Node.js                | v20.16.0                                         |
| home                   | C:\projects\MoonSlate\comp\node_modules\@sap\cds |

**Comment by daogrady** [comment]
Hi @333sachin ,

please provide a minimal reproducible example, thanks!

Best,
Daniel

**Comment by 333sachin** [comment]
Here's a minimum reproducible example. 

https://github.com/333sachin/issue-364

please run the below commands to get the error
```
cf login
cf push issue-364
```

**Comment by daogrady** [comment]
Thank you for the reproduction!
This could be related to the symlink we generate in `@types/sap__cds`.
Can you please try out [adjusting the `"types"`](https://cap.cloud.sap/docs/get-started/troubleshooting#type-definitions-for-sap-cds-not-found-or-incomplete) proerty in your _tsconfig.json_?

**Comment by 333sachin** [comment]
thanks @daogrady - but the sample was not a typescript project at all. 
I added typescript support with ```cds add typescript ```  and update the tsconfig.json file according to the link. 
I am able to run the project with cds-ts but still get the same error on cf push command 
https://github.com/333sachin/issue-364 is updated with the above changes. 

![image](https://github.com/user-attachments/assets/33e3332e-3fa1-4f33-b484-4d55fcfc9325)
![image](https://github.com/user-attachments/assets/d8cf4bc0-b1cb-46c3-95ed-a3091960aac3)

**Comment by daogrady** [comment]
Hi @333sachin ,

thanks for trying out the proposed solution (you probably could have stayed with pure JS and used a [_jsconfig.json_](https://code.visualstudio.com/docs/languages/jsconfig) instead, in case you don't want to migrate to TS with your actual app 🙂).

Now that the type resolution mechanism should be able to find cds-types based on your config file, can you please delete the *node_modules/@types/sap__cds* (which is just a symlink to *node_modules/cap-js/cds-types*) and try again?

Best,
Daniel

**Comment by 333sachin** [comment]
Thanks, 
Deleting the synlink worked for non ts project.
