### ISSUE TITLE
[BUG] `@types/express` should be `peerDependency` instead of hard dependency

### ISSUE THREAD

**Issue by hakimio** [cap-js/cds-types#375]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

`cds-types` causes errors when `@types/express` version listed in `cds-types` dependencies doesn't correspond to the one used in your own project.
Using `v5.0.0` in your own project conflicts with `v4.17.21` hard dependency listed in `cds-types` dependencies.

### Expected Behavior

User should be allowed to use `>=4.17.21` `@types/express` version without any errors.

### Versions

| Package            | Version                                                                              |
| ---------------------- | ----------------------------------------------------------------------------------------------------------- |
| @cap-js/asyncapi       | 1.0.2                                                                                                       |
| @cap-js/cds-types      | 0.8.0                                                                                                       |
| @cap-js/openapi        | 1.1.0                                                                                                       |
| @cap-js/postgres       | 1.10.4                                                                                                      |
| @sap/cds               | 8.5.1                                                                                                       |
| @sap/cds-compiler      | 5.5.2                                                                                                       |
| @sap/cds-dk            | 8.5.1                                                                                                       |
| @sap/cds-fiori         | 1.2.8                                                                                                       |
| @sap/cds-foss          | 5.0.1                                                                                                       |
| @sap/cds-mtxs          | 2.4.1                                                                                                       |
| @sap/eslint-plugin-cds | 3.1.2                                                                                                       |
| Node.js                | v20.18.0                                                                                                    |

**Comment by daogrady** [comment]
Hi Tomas,

thanks for your report. What are those errors?

Best,
Daniel

**Comment by daogrady** [comment]
Hi Tomas,

thanks for adding the error!
As express separates its types from its implementation, and we also have to support pure JS projects, we unfortunately cannot assume that user projects always have `@types/express` available. But I agree that the current situation is not satisfying and I will check back if we can _at least_ upgrade the dependency to v5.

Best,
Daniel

**Comment by hakimio** [comment]
If you use `npm` or `pnpm` `peerDependencies` will be installed automatically. No need for the user to do anything.
Only if you explicitly mark `peerDependency` as `optional`, the installation will be skipped.

**Comment by daogrady** [comment]
Hi Tomas,

thanks for pointing this out! This behaviour has indeed changed a few versions of npm ago and I was not aware of this. That does make this change much easier and viable.

Best,
Daniel
