### ISSUE TITLE
Missing Properties in EventContext

### ISSUE THREAD

**Issue by Raphael-Gisler-AGI** [cap-js/cds-types#41]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When writing cds.context in a handler the property path doesn't exists.
When writing it in the debugger it exists.

### Expected Behavior

I expected the property path to exists.

### References

It exists in the debugger

### Versions

| @cap-js/cds-types      | 0.2.0                                           |
| @cap-js/sqlite         | 1.6.0                                           |
| @sap/cds               | 7.8.0                                           |
| @sap/cds-compiler      | 4.8.0                                           |
| @sap/cds-dk (global)   | 7.7.2                                           |
| @sap/cds-fiori         | 1.2.3                                           |
| @sap/cds-foss          | 5.0.0                                           |
| @sap/cds-mtxs          | 1.16.0                                          |
| @sap/eslint-plugin-cds | 2.6.7                                           |
| Node.js                | v18.17.1                                        |

### Anything else? Logs?

There seem to be quite a lot of other properties in the debugger too.
I assume that some properties might be private and therefore aren't in this repo but I'm not sure.
Is there a reason why they aren't included?

![image](https://github.com/cap-js/cds-types/assets/144799331/de669087-d6c5-43ad-b383-100ffcf97971)

**Comment by daogrady** [comment]
Hi Raphael,

thanks for bringing this to our attention! I just checked the type in question and it seems like `.path` is present, but only for the [`Request` type](https://github.com/cap-js/cds-types/blob/main/apis/events.d.ts#L52), which in turn is an `Event` and therefore `EventContext` as well.
Could you please provide a use case where you expect the `.path` property? Maybe the type there should actually be `Request`, rather than `Event`.

Best,
Daniel

**Comment by Raphael-Gisler-AGI** [comment]
Hi Daniel
I'm trying to access the path property through ```cds.context```.
I currently have to cast it to ```any``` though because the ```path``` property doesn't exists.

![image](https://github.com/cap-js/cds-types/assets/144799331/96ebe51f-6510-4555-9a5e-9d04b06ce5e6)

![image](https://github.com/cap-js/cds-types/assets/144799331/b7bf7a2a-301f-417d-9179-db18b6bb223c)

**Comment by daogrady** [comment]
@johannes-vogel maybe you can shine some light on this.
The [relevant section in CAPire](https://cap.cloud.sap/docs/node.js/events#cds-context) reads as if `cds.context` should be typed as `EventContext` and therefore not have a `.path` property. Runtime behaviour seems to suggest the presence of `.path`, which would either

- indicate `cds.context` to either be of type `Request`, 
- or for `.path` to move up to `EventContext`.

Can you please advise?

**Comment by johannes-vogel** [comment]
Please only rely on the documented properties of `cds.context`. This is subject to change with the new protocol adapter implemented with cds8.

**Comment by daogrady** [comment]
Hi @Raphael-Gisler-AGI ,

we discussed your issue today:

The types as they are today are in fact correct. `cds.context` is meant to be of type `EventContext`, which is not supposed to expose a `.path` property.
The `.path` you are seeing in your debugger is inadvertently exposed here; please don't rely on it or use it.
We assume you actually want `currentEntity.name` or `req.path`, depending on your use case.
If this does not fix your issue, please feel free to re-open this issue with a full description of what you are trying to achieve/ what you want to use `cds.context.path` for.

Best,
Daniel
