### ISSUE TITLE
[BUG] Wrong method name for exists in utils.d.ts

### ISSUE THREAD

**Issue by skarolus-rc** [cap-js/cds-types#76]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The naming of the function "exist" is wrong in "utils.d.ts". 

### Expected Behavior

As described in the documentation, https://cap.cloud.sap/docs/node.js/cds-utils#async-read-file, it has to be "exists".

### References

const { read, exists } = cds.utils;

it does not find exists. Only "exist" is available. But in the utils.js file of cds, the function is called "exists".

### Versions

@cap-js/cds-typer: 0.20.2
@cap-js/cds-types: 0.2.0
@cap-js/sqlite: 1.7.1
@sap/cds: 7.9.2
@sap/cds-compiler: 4.9.4
@sap/cds-dk: 7.9.1
@sap/cds-dk (global): 7.9.2
@sap/cds-fiori: 1.2.3
@sap/cds-foss: 5.0.0
@sap/cds-mtxs: 1.18.1
@sap/eslint-plugin-cds: 3.0.3
Node.js: v20.12.0

**Comment by daogrady** [comment]
Hi Simon,

good catch, thanks for the report!

Best,
Daniel
